# Generated by Django 5.0.6 on 2024-05-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_remove_tipo_de_usuario_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='comuna',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.TextField(choices=[('Región de Arica y Parinacota', 'Arica y Parinacota'), ('Región de Tarapacá', 'Tarapacá'), ('Región de Antofagasta', 'Antofagasta'), ('Región de Atacama', 'Atacama'), ('Región de Coquimbo', 'Coquimbo'), ('Región de Valparaíso', 'Valparaiso'), ('Región Metropolitana de Santiago', 'RM'), ('Región Libertador General Bernardo O’Higgins', 'Libertador Bdo OHiggins'), ('Región del Maule', 'Maule'), ('Región del Ñuble', 'Ñuble'), ('Región del Biobío', 'Bio Bio'), ('Región de La Araucanía', 'Araucania'), ('Región de Los Ríos', 'Los Rios'), ('Región de Los Lagos', 'Los Lagos'), ('Región de Aysén del General Carlos Ibáñez del Campo', 'Aysén'), ('Región de Magallanes y la Antártica Chilena', 'Magallanes')]),
        ),
    ]
