# Generated by Django 5.0.6 on 2024-05-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_alter_comuna_comuna_alter_region_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(),
        ),
    ]
