# Generated by Django 5.0.6 on 2024-05-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_region_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_de_inmueble',
            name='tipo_de_inmueble',
            field=models.TextField(),
        ),
    ]
