# Generated by Django 5.0.6 on 2024-05-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_alter_tipo_de_inmueble_tipo_de_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='descripcion',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='m2_totales',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m2_contruidos',
            field=models.FloatField(default=0.0),
        ),
    ]
