# Generated by Django 5.0.6 on 2024-05-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_inmueble_descripcion_inmueble_m2_totales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='m2_contruidos',
            new_name='m2_construidos',
        ),
    ]
