# Generated by Django 5.0.6 on 2024-05-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_rename_m2_contruidos_inmueble_m2_construidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
