# Generated by Django 5.0.6 on 2024-06-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0008_alter_inmueble_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='precio_mensual_arriendo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='correo_electronico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_personal',
            field=models.CharField(max_length=50),
        ),
    ]
